# Generated by Django 4.1.3 on 2022-11-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_image",
            field=models.ImageField(null=True, upload_to="catgories"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(null=True, upload_to="product"),
        ),
    ]
